### ISSUE TITLE
Error Creating a New Elastic Profile

### ISSUE THREAD

**Issue by jhurley1** [gocd/azure-elastic-agent-plugin#9]
Hello,

I've setup a test GoCD server instance (version 20.3.0) and I'm experiencing a validation error when trying to create a new elastic profile.  It looks like this may be part of a validation routine trying to check the the image URN entered in the UI?  The specific fault is that the URN "OpenLogic:CentOS-CI:7-CI:latest" is being flagged as invalid even though I use this in other ARM templates that deploy fine.  Watching the GoCD log files (specifically the go-server.log) when clicking the "Save" button I see the exception below get dumped out:

`
2020-06-30 20:40:45,443 ERROR [179@MessageListener for ServerPingListener] JMSMessageListenerAdapter:87 - Exception thrown in message handling by listener com.thoughtworks.go.server.messag
ing.elasticagents.ServerPingListener@76b4eb12
java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter this.client.subscriptionId() is required and cannot be null.
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:214)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
        at com.thoughtworks.go.plugin.access.elastic.v4.ElasticAgentExtensionV4.serverPing(ElasticAgentExtensionV4.java:131)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentExtension.serverPing(ElasticAgentExtension.java:63)
        at com.thoughtworks.go.plugin.access.elastic.ElasticAgentPluginRegistry.serverPing(ElasticAgentPluginRegistry.java:51)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:31)
        at com.thoughtworks.go.server.messaging.elasticagents.ServerPingListener.onMessage(ServerPingListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Parameter this.client.subscriptionId() is required and cannot be null.
        at com.thoughtworks.gocd.elasticagent.azure.AzurePlugin.handle(AzurePlugin.java:105)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
        ... 11 common frames omitted
Caused by: java.lang.IllegalArgumentException: Parameter this.client.subscriptionId() is required and cannot be null.
        at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.listSinglePageAsync(VirtualMachinesInner.java:1689)
        at com.microsoft.azure.management.compute.implementation.VirtualMachinesInner.list(VirtualMachinesInner.java:1617)
        at com.microsoft.azure.management.resources.fluentcore.arm.collection.implementation.TopLevelModifiableResourcesImpl.list(TopLevelModifiableResourcesImpl.java:118)
        at com.thoughtworks.gocd.elasticagent.azure.client.GoCDAzureClient.virtualMachinesWithTag(GoCDAzureClient.java:205)
        at com.thoughtworks.gocd.elasticagent.azure.client.GoCDAzureClient.runningVirtualMachinesWithTag(GoCDAzureClient.java:177)
        at com.thoughtworks.gocd.elasticagent.azure.AzureInstanceManager.listInstances(AzureInstanceManager.java:65)
        at com.thoughtworks.gocd.elasticagent.azure.AzureAgentInstances.refreshAll(AzureAgentInstances.java:145)
        at com.thoughtworks.gocd.elasticagent.azure.AzurePlugin.refreshInstances(AzurePlugin.java:110)
        at com.thoughtworks.gocd.elasticagent.azure.AzurePlugin.handle(AzurePlugin.java:67)
        ... 13 common frames omitted
`

I don't see anywhere that a subscription ID is requested through either the plugin setup or the elastic profile creation so this is a bit confusing.  In order to create the cluster profile I followed the steps documented on the page below; again I didn't see any mention of setting a subscription ID in these steps:

https://github.com/gocd/azure-elastic-agent-plugin/blob/master/docs/ELASTIC_PROFILE_CONFIGURATION.md#create-an-elastic-agent-profile-for-azure

Screenshot of error in the UI:

![image](https://user-images.githubusercontent.com/2159449/86175715-73225e80-bae9-11ea-8f79-1b394c9c9b67.png)

Thank you for any help you can provide in explaining or helping to resolve this issue.

**Comment by arvindsv** [comment]
Can you check if the "Virtual network ID" is provided properly? See: https://github.com/gocd/azure-elastic-agent-plugin/blob/master/docs/PLUGIN_SETTINGS.md#azure-configuration

It needs to look like `/subscriptions/...` as shown in the image.

**Comment by jhurley1** [comment]
@arvindsv  - I provided the network ID shown below in the plugin configuration; note that the subscription ID was intentionally blanked out before posting as this is publicly viewable:

/subscriptions/********-****-****-****-*************/resourceGroups/CD_01-rg/providers/Microsoft.Network/virtualNetworks/CD_01-vnet

I also see that if I click the "Status Report" button on the plugin page I also get the same error (see note below but this is with the 1.0.0-4 version of the plugin):

![image](https://user-images.githubusercontent.com/2159449/86178042-4b34fa00-baed-11ea-9ace-c08bf8111536.png)

----------------------------

Additional information:

I started off using a custom built version of the plugin based on the tip of the code repository last week (revision 3273b9f2a638f658679099844e3a24c2a8fd40ea) and thought after opening this ticket that maybe I should have used a release tag instead.  I have since re-built the plugin I'm using based on the 'v1.0.0-4' tag.  The result is the same though; when trying to create a new elastic profile the save operation fails out with the same underlying cause previously posted (java.lang.IllegalArgumentException: Parameter this.client.subscriptionId() is required and cannot be null).

The reason for compiling this locally is that we cannot migrate our GoCD server past Java 11 at this time and the 1.0.0-4 release appears to have been compiled under Java 12.  To resolve the major/minor version error we got when loading the plugin I needed to create a custom build using Java 11 and test whether or not the plugin would work.

**Comment by arvindsv** [comment]
@jhurley1 Since you're able to compile it, can you check by changing [this line](https://github.com/gocd/azure-elastic-agent-plugin/blob/3273b9f2a638f658679099844e3a24c2a8fd40ea/src/main/java/com/thoughtworks/gocd/elasticagent/azure/client/GoCDAzureClientFactory.java#L43) to something like this:

```
        .withSubscription("YOUR_SUBSCRIPTION_ID_HERE");
```

... and provide the right subscription ID and see what happens?

Hypothesis: Your default subscription is not the one you're trying to create the VM in, and the correct subscription is not used.

If that works, we can look into adding subscription ID as a property and then taking that as an input.

**Comment by jhurley1** [comment]
@arvindsv  - That does indeed appear to be the problem.  Once I made the change you suggested validation is moving on during the profile setup.

**Comment by arvindsv** [comment]
@jhurley1 Great. Can you continue and let me know if everything else works? If so, then I'll make this change and publish a release.

**Comment by jhurley1** [comment]
@arvindsv  - Will do.  I'm working through some permission problems reported with my service principal right now; I'll update the ticket with my testing results once I move past that.  Thanks for the help with this!

**Comment by jhurley1** [comment]
@arvindsv  - I've completed testing and was able to both create a new elastic profile as well as use that profile to execute pipelines.  To me it looks like if the subscription ID can be provided as you suggested earlier (maybe separately as a field in the plugin settings or extracted from the virtual network ID?) that would resolve this issue and let the plugin be used in more complex Azure setups.

**Comment by arvindsv** [comment]
@jhurley1 Ok, I think it makes sense to extract it from the virtual network ID. I have a PR [open here](https://github.com/gocd/azure-elastic-agent-plugin/pull/10). Do you mind trying it? I've also changed the source compatibility to be Java 11. That way, the released version should work for you.

**Comment by jhurley1** [comment]
@arvindsv - I backed out all changes I've made locally and produced a plugin jar using your code from the PR; everything looks good and I see that my test pipeline works as expected as do things like the plugin status page.  Also thank you for changing the source compatibility version back to Java 11; this will make it much easier for us to pickup and use the next release.

**Comment by arvindsv** [comment]
@jhurley1 Great, thanks for checking. I merged #10. There is a new release out: https://github.com/gocd/azure-elastic-agent-plugin/releases/tag/v1.0.0-15-exp

It's experimental for now, but I can change that. However, during that time there was another commit, which might affect you specifically. The commit is: https://github.com/gocd/azure-elastic-agent-plugin/commit/7850354536b642b62f8fa85522725b5843ea8230

The main changes are to say that the plugin needs GoCD `20.5.0` and it installs the 20.5.0 GoCD agent using Java 13. The fact that it is Java 13 shouldn't affect you, since it is for running the agent only. The fact that the plugin will claim that it _needs_ 20.5.0 might be a problem for you.

I suspect it'll continue to work even with 20.3.0, but you'll need to verify it. I'll close this issue now.
